project:
  name: quickstart-grid-connect-connectsense
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: True
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - eu-north-1
    - eu-south-1
    - ap-southeast-2
    - ca-central-1
    - sa-east-1
    - af-south-1
tests:
  grid-connect-connectsense:
    parameters:
      QuickstartBucketName: "$[taskcat_autobucket]"
      QSS3KeyPrefix: "quickstart-grid-connect-connectsense/"
    template: templates/template.yaml
    regions:
      # - us-west-2
      # - us-east-2
      - us-east-1
      # - eu-west-1
      # - eu-central-1
      # - eu-west-2